from flask import Flask, render_template, jsonify
import yfinance as yf
import pandas as pd
import numpy as np
import os
import json
import time
from datetime import datetime

app = Flask(__name__)

HISTORY_FILE = "signal_history.json"


# =========================================================
# BIST HİSSE LİSTESİ
# =========================================================

BIST_HISSELERI = [
    "A1CAP.IS","ACSEL.IS","ADEL.IS","ADESE.IS","ADGYO.IS",
    "AEFES.IS","AFYON.IS","AGESA.IS","AGHOL.IS","AGROT.IS",
    "AGYO.IS","AHGAZ.IS","AKBNK.IS","AKCNS.IS","AKENR.IS",
    "AKFGY.IS","AKFYE.IS","AKGRT.IS","AKMGY.IS","AKSA.IS",
    "AKSEN.IS","AKSGY.IS","ALARK.IS","ALBRK.IS","ALCAR.IS",
    "ALCTL.IS","ALFAS.IS","ALGYO.IS","ALKA.IS","ALKIM.IS",
    "ALKLC.IS","ALMAD.IS","ALTNY.IS","ANELE.IS","ANGEN.IS",
    "ANHYT.IS","ANSGR.IS","ARASE.IS","ARCLK.IS","ARDYZ.IS",
    "ARENA.IS","ARMDA.IS","ARSAN.IS","ARTMS.IS","ARZUM.IS",
    "ASELS.IS","ASGYO.IS","ASTOR.IS","ASUZU.IS","ATAGY.IS",
    "ATAKP.IS","ATATP.IS","ATEKS.IS","AVGYO.IS","AVHOL.IS",
    "AVOD.IS","AVPGY.IS","AYCES.IS","AYDEM.IS","AYEN.IS",
    "AYGAZ.IS","AZTEK.IS","BAGFS.IS","BAHKM.IS","BAKAB.IS",
    "BALAT.IS","BANVT.IS","BARMA.IS","BASCM.IS","BASGZ.IS",
    "BAYRK.IS","BEGYO.IS","BERA.IS","BEYAZ.IS","BFREN.IS",
    "BIENY.IS","BIGEN.IS","BIGCH.IS","BIMAS.IS","BINHO.IS",
    "BIOEN.IS","BIZIM.IS","BJKAS.IS","BLCYT.IS","BMSCH.IS",
    "BMSTL.IS","BNTAS.IS","BOBET.IS","BORLS.IS","BORSK.IS",
    "BOSSA.IS","BRISA.IS","BRKO.IS","BRKSN.IS","BRKVY.IS",
    "BRLSM.IS","BRSAN.IS","BRYAT.IS","BSOKE.IS","BTCIM.IS",
    "BUCIM.IS","BURCE.IS","BURVA.IS","BVSAN.IS","BYDNR.IS",
    "CANTE.IS","CASA.IS","CATES.IS","CCOLA.IS","CELHA.IS",
    "CEMAS.IS","CEMTS.IS","CIMSA.IS","CLEBI.IS","CMBTN.IS",
    "CMENT.IS","CONSE.IS","COSMO.IS","CRDFA.IS","CRFSA.IS",
    "CUSAN.IS","CVKMD.IS","CWENE.IS","DAGHL.IS","DAGI.IS",
    "DAPGM.IS","DARDL.IS","DCTTR.IS","DENGE.IS","DERHL.IS",
    "DERIM.IS","DESA.IS","DESPC.IS","DEVA.IS","DGATE.IS",
    "DGNMO.IS","DITAS.IS","DMRGD.IS","DMSAS.IS","DNISI.IS",
    "DOAS.IS","DOBUR.IS","DOCO.IS","DOHOL.IS","DOKTA.IS",
    "DURDO.IS","DYOBY.IS","DZGYO.IS","EBEBK.IS","ECILC.IS",
    "ECZYT.IS","EDATA.IS","EDIP.IS","EFORC.IS","EGEEN.IS",
    "EGEPO.IS","EGGUB.IS","EGPRO.IS","EGSER.IS","EKGYO.IS",
    "EKOS.IS","EKSUN.IS","ELITE.IS","EMKEL.IS","EMNIS.IS",
    "ENDAE.IS","ENERY.IS","ENJSA.IS","ENKAI.IS","ENSRI.IS",
    "ENTRA.IS","EREGL.IS","ERSU.IS","ESCAR.IS","ESCOM.IS",
    "ESEN.IS","ETILR.IS","ETYAT.IS","EUHOL.IS","EUPWR.IS",
    "EUREN.IS","EYGYO.IS","FADE.IS","FENER.IS","FLAP.IS",
    "FMIZP.IS","FONET.IS","FORMT.IS","FORTE.IS","FRIGO.IS",
    "FROTO.IS","GARAN.IS","GEDIK.IS","GEDZA.IS","GENIL.IS",
    "GENTS.IS","GEREL.IS","GESAN.IS","GIPTA.IS","GLBMD.IS",
    "GLCVY.IS","GLRMK.IS","GLYHO.IS","GMTAS.IS","GOKNR.IS",
    "GOLTS.IS","GOODY.IS","GOZDE.IS","GRSEL.IS","GRTHO.IS",
    "GSDDE.IS","GSDHO.IS","GSRAY.IS","GUBRF.IS","GWIND.IS",
    "HATEK.IS","HATSN.IS","HDFGS.IS","HEDEF.IS","HEKTS.IS",
    "HKTM.IS","HLGYO.IS","HOROZ.IS","HRKET.IS","HTTBT.IS",
    "HUBVC.IS","HUNER.IS","ICBCT.IS","ICUGS.IS","IDEAS.IS",
    "IEYHO.IS","IHAAS.IS","IHEVA.IS","IHLAS.IS","IHLGM.IS",
    "IHYAY.IS","IMASM.IS","INDES.IS","INFO.IS","INGRM.IS",
    "INTEK.IS","INVEO.IS","INVES.IS","IPEKE.IS","ISCTR.IS",
    "ISDMR.IS","ISFIN.IS","ISGSY.IS","ISGYO.IS","ISKPL.IS",
    "ISKUR.IS","ISMEN.IS","ISSEN.IS","IZENR.IS","IZFAS.IS",
    "IZMDC.IS","JANTS.IS","KAPLM.IS","KAREL.IS","KARSN.IS",
    "KARTN.IS","KARYE.IS","KATMR.IS","KAYSE.IS","KBORU.IS",
    "KCAER.IS","KCHOL.IS","KENT.IS","KERVT.IS","KFEIN.IS",
    "KGYO.IS","KIMMR.IS","KLGYO.IS","KLKIM.IS","KLMSN.IS",
    "KLRHO.IS","KLSER.IS","KLYPV.IS","KMPUR.IS","KNFRT.IS",
    "KONKA.IS","KONTR.IS","KONYA.IS","KOPOL.IS","KORDS.IS",
    "KOTON.IS","KOZAA.IS","KOZAL.IS","KRDMA.IS","KRDMB.IS",
    "KRDMD.IS","KRGYO
